
CREATE DATABASE QUANLY_KHOHANG;
GO
USE QUANLY_KHOHANG;
GO

CREATE TABLE HANGHOA(
    MaHang VARCHAR(20) PRIMARY KEY,
	TenHang	NVARCHAR(255),
	MoTaHang NVARCHAR(1024),
	DonViTinh VARCHAR(10),
	GiaTriHang DECIMAL(18, 2)
);
CREATE TABLE KHOHANG(
    MaKho VARCHAR(20) PRIMARY KEY,
	TenKho NVARCHAR(255),
	DiaChiKho NVARCHAR(1024),
	SoLuongHang INT
);
CREATE TABLE NHAPHANG(
    MaNhapHang VARCHAR(20) PRIMARY KEY,
	NgayNhapHang DATETIME,
	MaHang VARCHAR(20),
	SoLuongNhap INT,
	GiaTriNhap DECIMAL(18 ,2),
	FOREIGN KEY (MaHang) REFERENCES HANGHOA(MaHang)
);
CREATE TABLE XUATHANG(
    MaXuatHang VARCHAR(20) PRIMARY KEY,
	NgayXuatHang DATETIME,
	MaHang VARCHAR(20),
	SoLuongXuat INT,
	GiaTriXuat DECIMAL(18, 2),
	FOREIGN KEY (MaHang) REFERENCES HANGHOA(MaHang)
);
CREATE TABLE NGUOIDUNG(
    MaNguoiDung VARCHAR(20) PRIMARY KEY,
	TenNguoiDung NVARCHAR(255),
	MatKhau NVARCHAR(255),
	QuyenTruyCap INT
);
CREATE TABLE BAOCAO(
    MaBaoCao VARCHAR(20) PRIMARY KEY,
    NgayBaoCao DATETIME,
    LoaiBaoCao INT,
    SoLieuBaoCao NVARCHAR(1024)
);
CREATE TABLE CANHBAO(
    MaCanhBao VARCHAR(20) PRIMARY KEY,
	LoaiCanhBao INT,
	NgayCanhBao DATETIME,
	NoiDungCanhBao NVARCHAR(1024)
);